all:
  vars:
    ansible_user: xdew
    ansible_python_interpreter: /usr/bin/python3.12

  children:
    cluster:
      children:
        master:
          hosts:
            xdew01:
              ansible_host: "{{ xdew01_ip }}"
              ansible_port: "{{ xdew01_port }}"

        worker:
          hosts:
            xdew02:
              ansible_host: "{{ xdew02_ip }}"
              ansible_port: "{{ xdew02_port }}"
            xdew03:
              ansible_host: "{{ xdew03_ip }}"
              ansible_port: "{{ xdew03_port }}"

    nas:
      hosts:
        xdew-nas:
          ansible_host: "{{ nas_ip }}"
          ansible_port: "{{ nas_port }}"

    local:
      hosts:
        localhost:
          ansible_connection: local
          ansible_host: localhost
