k3s_version: v1.32.2+k3s1
k3s_token: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=48') }}"
k3s_server_location: /var/lib/rancher/k3s
k3s_use_embedded_etcd: true
cluster_domain: cluster."{{ base_hostname }}"
